In [48]:
import numpy as np
import pandas as pd

In [49]:
df=pd.read_csv('/content/titanic - titanic.csv')

In [50]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [52]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [53]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [54]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [56]:
df.describe(include="float")

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [57]:
df.describe(include="int")

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [58]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [59]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [60]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [61]:
df['Age']=df['Age'].fillna(df['Age'].mode()[0])

In [62]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [63]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [64]:
df['Cabin']=df['Cabin'].fillna(df['Cabin'].mode()[0])

In [65]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S

In [66]:
df.dropna(subset=['Embarked'], inplace=True)

In [67]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [68]:
df['Cabin'].unique()

array(['B96 B98', 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'C83', 'F33', 'F G73',
       'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69',
       'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32',
       'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87',
       'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49',
       'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66',
       'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128',
       'D37', 'B35', 'E50', 'C82', 'E10', 'E44', 'A34', 'C104', 'C111',
       'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30', 'D20',
       'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22', 'C86',
       'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19',
       'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126', 'B71',
       'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64', 'E24',
       'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30', 'E121', 'D11',
       'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36', 'B102', 'B69',
       'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42', 'C148'],
      dtype=object)

In [69]:
df['Cabin'].value_counts()

Cabin
B96 B98        691
G6               4
C23 C25 C27      4
F33              3
F2               3
              ...
E17              1
A24              1
C50              1
B42              1
C148             1
Name: count, Length: 146, dtype: int64

In [70]:
df['Fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  83.475 ,  27.9   ,
        15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,  56.4958,
         7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,
        47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,  34.6542,
        63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,  24.15  ,
         9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,   6.975 ,
         7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,  79.2   ,
         6.75  ,  11.5   ,  36.75  ,   7.7958,  12.525 ,  66.6   ,
         7.3125,  61.3792,   7.7333,  69.55  ,  16.1   ,  15.75  ,
        20.525 ,  55.    ,  25.925 ,  33.5   ,  30.6958,  25.4667,
        28.7125,   0.    ,  15.05  ,  39.    ,  22.025 ,  50.    ,
         8.4042,   6.4958,  10.4625,  18.7875,  31.    , 113.275 ,
        27.    ,  76.2917,  90.    ,   9.35  ,  13.5   ,   7.55  ,
        26.25  ,  12.275 ,   7.125 ,  52.5542,  20.2125,  86.5   ,
       512.3292,  79.65  , 153.4625, 135.6333,  19.5   ,  29.7   ,
        77.9583,  20.25  ,  78.85  ,  91.0792,  12.875 ,   8.85  ,
       151.55  ,  30.5   ,  23.25  ,  12.35  , 110.8833, 108.9   ,
        24.    ,  56.9292,  83.1583, 262.375 ,  14.    , 164.8667,
       134.5   ,   6.2375,  57.9792,  28.5   , 133.65  ,  15.9   ,
         9.225 ,  35.    ,  75.25  ,  69.3   ,  55.4417, 211.5   ,
         4.0125, 227.525 ,  15.7417,   7.7292,  12.    , 120.    ,
        12.65  ,  18.75  ,   6.8583,  32.5   ,   7.875 ,  14.4   ,
        55.9   ,   8.1125,  81.8583,  19.2583,  19.9667,  89.1042,
        38.5   ,   7.725 ,  13.7917,   9.8375,   7.0458,   7.5208,
        12.2875,   9.5875,  49.5042,  78.2667,  15.1   ,   7.6292,
        22.525 ,  26.2875,  59.4   ,   7.4958,  34.0208,  93.5   ,
       221.7792, 106.425 ,  49.5   ,  71.    ,  13.8625,   7.8292,
        39.6   ,  17.4   ,  51.4792,  26.3875,  30.    ,  40.125 ,
         8.7125,  15.    ,  33.    ,  42.4   ,  15.55  ,  65.    ,
        32.3208,   7.0542,   8.4333,  25.5875,   9.8417,   8.1375,
        10.1708, 211.3375,  57.    ,  13.4167,   7.7417,   9.4833,
         7.7375,   8.3625,  23.45  ,  25.9292,   8.6833,   8.5167,
         7.8875,  37.0042,   6.45  ,   6.95  ,   8.3   ,   6.4375,
        39.4   ,  14.1083,  13.8583,  50.4958,   5.    ,   9.8458,
        10.5167])

In [71]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S

In [72]:
#one hot encoding
pd.get_dummies(df['Sex'])

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[889 rows x 2 columns]

In [73]:
#label encoding
from sklearn.preprocessing import LabelEncoder

In [74]:
le2=LabelEncoder()
df['Name']=le2.fit_transform(df['Name'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,190,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,353,female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,272,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,15,male,35.0,0,0,373450,8.0500,B96 B98,S

In [75]:
le3=LabelEncoder()
df['Ticket']=le3.fit_transform(df['Ticket'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,male,22.0,1,0,522,7.2500,B96 B98,S
1,2,1,1,190,female,38.0,1,0,595,71.2833,C85,C
2,3,1,3,353,female,26.0,0,0,668,7.9250,B96 B98,S
3,4,1,1,272,female,35.0,1,0,48,53.1000,C123,S
4,5,0,3,15,male,35.0,0,0,471,8.0500,B96 B98,S

In [76]:
le4=LabelEncoder()
df['Cabin']=le4.fit_transform(df['Cabin'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,male,22.0,1,0,522,7.2500,46,S
1,2,1,1,190,female,38.0,1,0,595,71.2833,80,C
2,3,1,3,353,female,26.0,0,0,668,7.9250,46,S
3,4,1,1,272,female,35.0,1,0,48,53.1000,54,S
4,5,0,3,15,male,35.0,0,0,471,8.0500,46,S

In [77]:
#Manual encoding
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [80]:
df['Sex']=df['Sex'].replace({'female':0,'male':1})
df.head()

/tmp/ipython-input-80-3941162205.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex']=df['Sex'].replace({'female':0,'male':1})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,522,7.2500,46,S
1,2,1,1,190,0,38.0,1,0,595,71.2833,80,C
2,3,1,3,353,0,26.0,0,0,668,7.9250,46,S
3,4,1,1,272,0,35.0,1,0,48,53.1000,54,S
4,5,0,3,15,1,35.0,0,0,471,8.0500,46,S

In [85]:
df.Embarked.unique()

array([0, 1, 2])

In [82]:
df['Embarked']=df['Embarked'].replace({'S':0,'C':1,'Q':2})
df.head()

/tmp/ipython-input-82-1358648033.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Embarked']=df['Embarked'].replace({'S':0,'C':1,'Q':2})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,522,7.2500,46,0
1,2,1,1,190,0,38.0,1,0,595,71.2833,80,1
2,3,1,3,353,0,26.0,0,0,668,7.9250,46,0
3,4,1,1,272,0,35.0,1,0,48,53.1000,54,0
4,5,0,3,15,1,35.0,0,0,471,8.0500,46,0

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    int64
 4   Sex          889 non-null    int64
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    int64
 9   Fare         889 non-null    float64
 10  Cabin        889 non-null    int64
 11  Embarked     889 non-null    int64
dtypes: float64(2), int64(10)
memory usage: 90.3 KB